export const extensionToLanguage: {
  [key: string]: string;
} = {
  svg: 'svg',
  json: 'json',
  css: 'css',
  js: 'javascript',
  php: 'php',
  c: 'c',
  cpp: 'cplusplus',
  cs: 'csharp',
  java: 'java',
  py: 'python',
  rb: 'ruby',
  ts: 'typescript',
  jsx: 'react',
  tsx: 'react',
  html: 'html',
  sql: 'sql',
  go: 'go',
  swift: 'swift',
  m: 'objectivec',
  hs: 'haskell',
  kt: 'kotlin',
  rs: 'rust',
  lua: 'lua',
  r: 'r',
  pl: 'perl',
  scala: 'scala',
  elm: 'elm',
  clj: 'clojure',
  cljs: 'clojure',
  ex: 'elixir',
  erl: 'erlang',
  md: 'markdown',
  sass: 'sass',
  scss: 'sass',
  less: 'less',
  vue: 'vuejs',
  svelte: 'svelte',
  mjs: 'javascript',
  cjs: 'javascript',
  coffee: 'coffeescript',
  sh: 'bash',
  bash: 'bash',
  yml: 'yaml',
  yaml: 'yaml',
  ml: 'ocaml',
  fs: 'fsharp',
  dart: 'dart',
  groovy: 'groovy',
  gd: 'godot',
  tex: 'latex',

  // blockchains
  sol: 'solidity',
};
